#!/bin/sh
# Copyright (C) 2010  Daniel Richman
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# For a full copy of the GNU General Public License,
# see <http://www.gnu.org/licenses/>.

cd $HABITAT

cat <<-EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <title>habitat</title>
    <style type="text/css">
      body { font-family: sans-serif; }
      #title { font-size: 3em; padding-top: 1em; padding-bottom: 0.8em; text-align: center; color: #000088; }
      #page { width: 80%; margin: 0 auto; }
      #updated { color: #888; }
      .small, #updated { font-size: 80%; }
    </style>
  </head>
  <body>

<div id="title">habitat</div>

<div id="page">
  <p>
    habitat is a system for uploading, processing, storing and displaying
    telemetry and related information transmitted from high altitude balloons.

    The back end is written in Python and is responsible for parsing incoming
    data and storing it in the database, while the frontend is written
    independently in JavaScript and HTML and communicates with CouchDB
    directly to obtain data and display it.
  </p>

  <ul>
    <li><a href="docs">Pretty documentation!</a></li>
    <li>
      <a href="http://github.com/ukhas/habitat">Browse habitat's source on github</a>
      <span class="small"><a href="source">(mirror)</a></span>
    </li>
    <li><a href="https://www.pivotaltracker.com/projects/112268">habitat on Pivotal Tracker</a> (roadmap, etc.)</li>
    <li><a href="http://ci.habhub.org/">habitat's continuous integration server</a></li>
    <li>
      <code>git checkout git://github.com/ukhas/habitat.git</code>
      <span class="small">(mirror at <code><a href="habitat.git">http://habitat.habhub.org/habitat.git</a></code>)</span>
    </li>
    <li>
      Latest GIT snapshot available at <a href="https://github.com/ukhas/habitat/archives/develop">github</a>;
      <span class="small"><a href="habitat.tar.gz">(mirror)</a></span>
    </li>
  </ul>

  <p>
    <a href='http://habhub.org/'>habhub.org</a>
  </p>

  <pre id="updated">
EOF

echo -n "habitat.habhub.org last updated: "
date
echo

git log -1 | $SANITISER

cat <<-EOF
  </pre>
</div>

  </body>
</html>

EOF
