#!/bin/sh
# Copyright (C) 2010  Daniel Richman
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# For a full copy of the GNU General Public License,
# see <http://www.gnu.org/licenses/>.

ROOT=/home/habitat-www
HABITAT=$ROOT/habitat
DOCS=$HABITAT/docs
OUTPUT=$ROOT/rendered-docs
TAR=$ROOT/habitat.tar
GENHOMEPAGE=$ROOT/genhomepage
HOMEPAGE=$ROOT/index.html
SANITISER="python $ROOT/sanitise.py"

cd $HABITAT
git fetch origin develop
git reset --hard FETCH_HEAD
git clean -fxd

sphinx-build -Eb html $DOCS $OUTPUT
git clean -fxd
git gc

git archive --format tar -o $TAR --prefix habitat/ HEAD
gzip -f -9 $TAR

export HABITAT
export SANITISER
$GENHOMEPAGE > $HOMEPAGE
